### ISSUE TITLE
Already initialized/paused/whatever

### ISSUE THREAD

**Issue by Foxie117** [BinkanSalaryman/Discord-Audio-Stream-Bot#37]
So the bot does connect but keeps being silent. 

This is what i get in the log file

18:29:53.849 [JDA AudioWS-ReadThread (guildId: 628287437159792690)] ERROR DiscordAudioStreamBot - Failed to pause/unpause speak handler for guild TestServer
net.runee.errors.BassException: Already initialized/paused/whatever
	at net.runee.misc.Utils.checkBassError(Utils.java:251)
	at net.runee.SpeakHandler.setPlaying(SpeakHandler.java:79)
	at net.runee.DiscordAudioStreamBot$1.onStatusChange(DiscordAudioStreamBot.java:310)
	at net.dv8tion.jda.api.audio.hooks.ListenerProxy.onStatusChange(ListenerProxy.java:60)
	at net.dv8tion.jda.internal.audio.AudioWebSocket.changeStatus(AudioWebSocket.java:215)
	at net.dv8tion.jda.internal.audio.AudioWebSocket.handleEvent(AudioWebSocket.java:443)
	at net.dv8tion.jda.internal.audio.AudioWebSocket.onTextMessage(AudioWebSocket.java:281)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:369)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:969)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:752)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
18:29:54.152 [JDA AudioConnection Guild: 628287437159792690 Sending Thread] WARN SpeakHandler - SpeakHandler is 212 ms behind! Clearing queue...

**Comment by Foxie117** [comment]
Seems like this program doesn't work with voicemeeter

**Comment by BinkanSalaryman** [comment]
Usually "BassException: Already initialized/paused/whatever" isn't a big issue, and re-logging/connecting should fix it for sure. I don't know about voicemeeter interactions though.
