### ISSUE TITLE
Autojoin not working

### ISSUE THREAD

**Issue by RdJNL** [BinkanSalaryman/Discord-Audio-Stream-Bot#38]
I'm trying to get autojoin to work, but no success so far. My audio channel is called _algemeen_.

I've tried adding it using these commands:
`@<botname> autojoin set algemeen`
`@<botname> autojoin set "algemeen"`

But I'm getting this exception in the log:
```
19:54:03.075 [JDA MainWS-ReadThread] ERROR CommandContext - Failed to execute command 'autojoin set algemeen'
java.lang.NullPointerException
	at net.runee.commands.audio.AutoJoinVoiceCommand.setAutoVoiceChannel(AutoJoinVoiceCommand.java:83)
	at net.runee.commands.audio.AutoJoinVoiceCommand.execute(AutoJoinVoiceCommand.java:72)
	at net.runee.misc.discord.CommandContext.run(CommandContext.java:68)
	at net.runee.DiscordAudioStreamBot.onCommandReceived(DiscordAudioStreamBot.java:262)
	at net.runee.DiscordAudioStreamBot.onMessageReceived(DiscordAudioStreamBot.java:222)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:428)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:82)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:69)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:152)
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:954)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:841)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:819)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

Am I doing something wrong?

**Comment by BinkanSalaryman** [comment]
This is definitly a bug.
