### ISSUE TITLE
superclass access check failed

### ISSUE THREAD

**Issue by JohnB17** [BinkanSalaryman/Discord-Audio-Stream-Bot#45]
I ran `run win64.bat` but it errored out and this is what was in `app.log`

```
18:22:22 [main] INFO  net.runee.gui.MainFrame - Hello World!
18:22:22 [main] ERROR net.runee.gui.MainFrame - Uncaught exception in thread main
java.lang.IllegalAccessError: superclass access check failed: class com.jgoodies.looks.windows.WindowsLookAndFeel (in unnamed module @0x21a947fe) cannot access class com.sun.java.swing.plaf.windows.WindowsLookAndFeel (in module java.desktop) because module java.desktop does not export com.sun.java.swing.plaf.windows to unnamed module @0x21a947fe
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[na:na]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:855) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:753) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:466) ~[na:na]
	at java.desktop/javax.swing.SwingUtilities.loadSystemClass(SwingUtilities.java:2035) ~[na:na]
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:637) ~[na:na]
	at net.runee.gui.MainFrame.main(MainFrame.java:46) ~[Discord%20Audio%20Stream%20Bot.jar:na]
18:22:28 [DASB Shutdown Hook] INFO  net.runee.gui.MainFrame - Goodbye!
```

**Comment by BinkanSalaryman** [comment]
This looks familiar to #44, could you please check your java installations?

**Comment by JohnB17** [comment]
I have Java 16 runtime environment and development kit.

**Comment by BinkanSalaryman** [comment]
Try uninstalling JDK 16 like xiopipe did for the previous issue
