### ISSUE TITLE
"Fatal Error" when opening the bat

### ISSUE THREAD

**Issue by muertom** [BinkanSalaryman/Discord-Audio-Stream-Bot#48]
Hello! when i try to run the bat i get "A fatal error occurred and the application will be closed"
This is what it says on the log:

12:20:02 [main] INFO  net.runee.gui.MainFrame - Hello World!
12:20:02 [main] ERROR net.runee.gui.MainFrame - Uncaught exception in thread main
java.lang.IllegalAccessError: superclass access check failed: class com.jgoodies.looks.windows.WindowsLookAndFeel (in unnamed module @0x10b48321) cannot access class com.sun.java.swing.plaf.windows.WindowsLookAndFeel (in module java.desktop) because module java.desktop does not export com.sun.java.swing.plaf.windows to unnamed module @0x10b48321
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[na:na]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:855) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:753) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:466) ~[na:na]
	at java.desktop/javax.swing.SwingUtilities.loadSystemClass(SwingUtilities.java:2035) ~[na:na]
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:637) ~[na:na]
	at net.runee.gui.MainFrame.main(MainFrame.java:46) ~[Discord%20Audio%20Stream%20Bot.jar:na]
12:20:04 [DASB Shutdown Hook] INFO  net.runee.gui.MainFrame - Goodbye!

I don't know what the problem is or how to solve it, thank you very much!

**Comment by muertom** [comment]
oops sorry, i saw the solution on the closed issues, it was to uninstall Java SE Development Kit 16
