### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by wolfy01** [BinkanSalaryman/Discord-Audio-Stream-Bot#53]
This is the error in logs:
```
20:27:32 [main] INFO  net.runee.gui.MainFrame - Hello World!
20:27:32 [main] ERROR net.runee.gui.MainFrame - Uncaught exception in thread main
java.lang.IllegalAccessError: superclass access check failed: class com.jgoodies.looks.windows.WindowsLookAndFeel (in unnamed module @0x6a79c292) cannot access class com.sun.java.swing.plaf.windows.WindowsLookAndFeel (in module java.desktop) because module java.desktop does not export com.sun.java.swing.plaf.windows to unnamed module @0x6a79c292
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[na:na]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:855) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:753) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:466) ~[na:na]
	at java.desktop/javax.swing.SwingUtilities.loadSystemClass(SwingUtilities.java:2035) ~[na:na]
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:637) ~[na:na]
	at net.runee.gui.MainFrame.main(MainFrame.java:46) ~[Discord%20Audio%20Stream%20Bot.jar:na]
20:27:34 [DASB Shutdown Hook] INFO  net.runee.gui.MainFrame - Goodbye!

```

**Comment by wolfy01** [comment]
Seems this is caused by using OPENJDK instead of normal java

**Comment by BinkanSalaryman** [comment]
Hmm, from what I've understood, this seems to be a bug of Java 9. I'm not sure what to do about it - I mean, I could catch this exception and give an dialog option to ignore it as a workaround, thus not load the L&F. But as for a real solution - no idea... You are probably better off installing a different java version (and pointing to that from the batch file if you wanna keep both versions).

**Comment by wolfy01** [comment]
The weird thing is I have java 16 as well, along side OpenJdk's java jre, uninstalling OpenJdk is all it took to fix it
