### ISSUE TITLE
Crash when launching app 

### ISSUE THREAD

**Issue by Chronolegionnaire** [BinkanSalaryman/Discord-Audio-Stream-Bot#61]
Bot program suddenly started crashing with fatal error on windows 10 when attempting to launch attempted launching with win32 and win64 as well as opening the .jar with javaw directly. Tried launching with jdk 8, 9, 10, and 17

19:26:08.351 [main] INFO MainFrame - Hello World!
19:26:08.377 [main] ERROR MainFrame - Uncaught exception in thread main
java.lang.IllegalAccessError: superclass access check failed: class com.jgoodies.looks.windows.WindowsLookAndFeel (in unnamed module @0x6d8a00e3) cannot access class com.sun.java.swing.plaf.windows.WindowsLookAndFeel (in module java.desktop) because module java.desktop does not export com.sun.java.swing.plaf.windows to unnamed module @0x6d8a00e3
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.desktop/javax.swing.SwingUtilities.loadSystemClass(SwingUtilities.java:2036)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:638)
	at net.runee.gui.MainFrame.main(MainFrame.java:44)
19:26:09.343 [DASB Shutdown Hook] INFO MainFrame - Goodbye!

**Comment by BinkanSalaryman** [comment]
Guess I need to check on that one if switching jdk and BASS natives doesn't change anything

**Comment by BinkanSalaryman** [comment]
Turns out this can be easily fixed by adding `--add-exports="java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED"` to the command line arguments (between `javaw` and `-jar`).
