### ISSUE TITLE
Fatal Error on connect

### ISSUE THREAD

**Issue by FoxyLight** [BinkanSalaryman/Discord-Audio-Stream-Bot#63]
Hello,
I'm getting a fatal error every time I click connect. Everything worked fine yesterday and I haven't made any changes since. Here is my app.log:  

```
12:56:26 [main] INFO  net.runee.gui.MainFrame - Hello World!
12:56:26 [main] INFO  net.runee.misc.Utils - ----------------------------
12:56:26 [main] INFO  net.runee.misc.Utils - Operating system: Windows 10
12:56:26 [main] INFO  net.runee.misc.Utils - OS architecture : amd64     
12:56:26 [main] INFO  net.runee.misc.Utils - Java version    : 17.0.2    
12:56:26 [main] INFO  net.runee.misc.Utils - Available cores : 12        
12:56:26 [main] INFO  net.runee.misc.Utils - Available memory: 8172 MB   
12:56:26 [main] INFO  net.runee.misc.Utils - ----------------------------
12:56:27 [AWT-EventQueue-0] INFO  net.runee.DiscordAudioStreamBot - Logging in...
12:56:27 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Automatically disabled CacheFlags due to missing intents
12:56:27 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.ACTIVITY (missing GatewayIntent.GUILD_PRESENCES)
12:56:27 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.EMOTE (missing GatewayIntent.GUILD_EMOJIS)
12:56:27 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.CLIENT_STATUS (missing GatewayIntent.GUILD_PRESENCES)
12:56:27 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.ONLINE_STATUS (missing GatewayIntent.GUILD_PRESENCES)
12:56:27 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - You can manually disable these flags to remove this warning by using disableCache(CacheFlag.ACTIVITY, CacheFlag.EMOTE, CacheFlag.CLIENT_STATUS, CacheFlag.ONLINE_STATUS) on your JDABuilder
12:56:27 [JDA RateLimit-Worker 1] DEBUG n.d.jda.internal.requests.Requester - Received response with following cf-rays: [6e8dca7a9a040c07-DFW]
12:56:27 [JDA RateLimit-Worker 2] DEBUG n.d.jda.internal.requests.Requester - Requesting GET -> https://discord.com/api/v8/users/@me returned status 503... retrying (attempt 1)
12:56:27 [JDA RateLimit-Worker 2] DEBUG n.d.jda.internal.requests.Requester - Requesting GET -> https://discord.com/api/v8/users/@me returned status 503... retrying (attempt 2)
12:56:27 [JDA RateLimit-Worker 2] DEBUG n.d.jda.internal.requests.Requester - Requesting GET -> https://discord.com/api/v8/users/@me returned status 503... retrying (attempt 3)
12:56:28 [AWT-EventQueue-0] ERROR net.runee.gui.MainFrame - Uncaught exception in thread AWT-EventQueue-0
net.dv8tion.jda.api.exceptions.ErrorResponseException: 503: N/A
	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:633)
	at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:374)
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:301)
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:268)
	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1870)
	at net.runee.DiscordAudioStreamBot.login(DiscordAudioStreamBot.java:122)
	at net.runee.gui.components.HomePanel.loginButtonPressed(HomePanel.java:115)
	at net.runee.gui.MainFrame$1.windowOpened(MainFrame.java:99)
	at java.desktop/java.awt.Window.processWindowEvent(Window.java:2082)
	at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
	at java.desktop/java.awt.Window.processEvent(Window.java:2044)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: net.dv8tion.jda.api.exceptions.ContextException: null
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
	at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
	at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
	... 32 common frames omitted
12:56:29 [DASB Shutdown Hook] INFO  net.runee.gui.MainFrame - Goodbye!

```

I have uninstalled and reinstalled Java. Installed a fresh version of the bot to no avail. Any help would be appreciated. Love the bot.
Thank you.

**Comment by FoxyLight** [comment]
Looks like it might be a Discord issue. Will update soon.

**Comment by FoxyLight** [comment]
Discord API is currently having problems so I will assume that is the issue and close the ticket for now. Thank you again for the amazing bot!
