### ISSUE TITLE
Unable to acces jarfile

### ISSUE THREAD

**Issue by PhastTraveler** [BinkanSalaryman/Discord-Audio-Stream-Bot#67]
When I start the file "run win64.bat"  An error popup appears saying "Unable to acces jarfile Discord Audio Stream Bot.jar.
![imagem_2023-01-21_224650475](https://user-images.githubusercontent.com/84929608/213897036-4733e8e4-b8de-4deb-9438-b07cb0fd350a.png)
![imagem_2023-01-21_224709825](https://user-images.githubusercontent.com/84929608/213897043-0bfb29d2-a825-4b7f-be10-065d354d34c0.png)

**Comment by BinkanSalaryman** [comment]
"
Right click the jarfile in question. Click properties. Click the unblock tab in bottom right corner. The file was blocked, because it was downloaded and not created on my PC.
"

Does this work for you?

**Comment by PhastTraveler** [comment]
It didn't work still show the same message

**Comment by ODENYGG** [comment]
Same here. Updated today from 2020 release now it's acting up. Old version still works though.

`15:21:50 [main] INFO  net.runee.gui.MainFrame - Hello World!
15:21:50 [main] INFO  net.runee.misc.Utils - ----------------------------
15:21:50 [main] INFO  net.runee.misc.Utils - Operating system: Windows 10
15:21:50 [main] INFO  net.runee.misc.Utils - OS architecture : amd64     
15:21:50 [main] INFO  net.runee.misc.Utils - Java version    : 1.8.0_321 
15:21:50 [main] INFO  net.runee.misc.Utils - Available cores : 16        
15:21:50 [main] INFO  net.runee.misc.Utils - Available memory: 3628 MB   
15:21:50 [main] INFO  net.runee.misc.Utils - ----------------------------
15:21:50 [main] ERROR net.runee.gui.MainFrame - Uncaught exception in thread main
jouvieje.bass.exceptions.BassException: no bass in java.library.path or org.lwjgl.librarypath
	at jouvieje.bass.BassInit.loadLibraries(BassInit.java:96)
	at net.runee.gui.MainFrame.main(MainFrame.java:55)
15:21:56 [DASB Shutdown Hook] INFO  net.runee.gui.MainFrame - Goodbye!
`

**Comment by ODENYGG** [comment]
UPDATE: I'm ashamed to admit it, but i solved my problem by just... updating java. That did it for me.

**Comment by WoozyMammoth** [comment]
I am having this same issue, java is up to date

**Comment by BinkanSalaryman** [comment]
Maybe it is blocked by windows. Try: Right click the "Disord Audio Stream Bot.jar" file. Click properties. Click the unblock tab in bottom right corner.
