### ISSUE TITLE
building with gradle only works with 03-23 version & program will not start with arm64 based java

### ISSUE THREAD

**Issue by nbmusic098** [BinkanSalaryman/Discord-Audio-Stream-Bot#74]
i've been building and using this project and have noticed a few errors mostly during building with gradle & launching the application

i'm using a macbook pro m2 max with apple silicon btw

i've managed to successfully build the gradle project, but only with the 03-23 update, attempting to build with the 03-25 update gives back this error:

```
A problem occurred evaluating root project 'Discord-Audio-Stream-Bot'.
> Unrecognized operating system: Mac OS X
```

i'm using the latest version gradle (8.0.2), i've tried downgrading, but it reports back it needing version 8.0+. attempting to change java versions does change the error message, but doesn't end up working.

speaking of java, when i did finally build the gradle project and launch into the application, it would always send an error message that looked like this

```
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
16:21:50 [main] INFO  net.runee.gui.MainFrame - Hello World!
16:21:50 [main] INFO  net.runee.misc.Utils - --------------------------
16:21:50 [main] INFO  net.runee.misc.Utils - Operating system: Mac OS X
16:21:50 [main] INFO  net.runee.misc.Utils - OS architecture : aarch64 
16:21:50 [main] INFO  net.runee.misc.Utils - Java version    : 17.0.1  
16:21:50 [main] INFO  net.runee.misc.Utils - Available cores : 12      
16:21:50 [main] INFO  net.runee.misc.Utils - Available memory: 16384 MB
16:21:50 [main] INFO  net.runee.misc.Utils - --------------------------
16:21:50 [main] ERROR net.runee.gui.MainFrame - Uncaught exception in thread main
jouvieje.bass.exceptions.BassException: no bass in java.library.path or org.lwjgl.librarypath
	at jouvieje.bass.BassInit.loadLibraries(BassInit.java:96)
	at net.runee.gui.MainFrame.main(MainFrame.java:55)
2023-04-08 16:21:52.054 java[7922:67679] Bad JNI lookup accessibilityHitTest
2023-04-08 16:21:52.055 java[7922:67679] (
	0   libawt_lwawt.dylib                  0x00000001031b60b4 -[JavaComponentAccessibility accessibilityHitTest:withEnv:] + 160
	1   libawt_lwawt.dylib                  0x00000001031657d4 -[AWTView accessibilityHitTest:] + 180
	2   AppKit                              0x00000001a0d9f064 -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 324
	3   AppKit                              0x00000001a0936c74 -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 264
	4   AppKit                              0x00000001a08ff524 CopyElementAtPosition + 152
	5   HIServices                          0x00000001a2b22818 _AXXMIGCopyElementAtPosition + 384
	6   HIServices                          0x00000001a2b47dc8 _XCopyElementAtPosition + 356
	7   HIServices                          0x00000001a2b0052c mshMIGPerform + 204
	8   CoreFoundation                      0x000000019d392ca0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
	9   CoreFoundation                      0x000000019d392bc0 __CFRunLoopDoSource1 + 520
	10  CoreFoundation                      0x000000019d3915a0 __CFRunLoopRun + 2240
	11  CoreFoundation                      0x000000019d39058c CFRunLoopRunSpecific + 612
	12  HIToolbox                           0x00000001a6bc5df4 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x00000001a6bc5c30 ReceiveNextEventCommon + 648
	14  HIToolbox                           0x00000001a6bc5988 _BlockUntilNextEventMatchingListInModeWithFilter + 76
	15  AppKit                              0x00000001a05aff58 _DPSNextEvent + 636
	16  AppKit                              0x00000001a05af0f4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
	17  libosxapp.dylib                     0x0000000102ee4220 -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 144
	18  AppKit                              0x00000001a05a3558 -[NSApplication run] + 464
	19  libosxapp.dylib                     0x0000000102ee3fd8 +[NSApplicationAWT runAWTLoopWithApp:] + 208
	20  libawt_lwawt.dylib                  0x00000001031be524 +[AWTStarter starter:headless:] + 488
	21  libosxapp.dylib                     0x0000000102ee5c50 +[ThreadUtilities invokeBlockCopy:] + 28
	22  Foundation                          0x000000019e325d54 __NSThreadPerformPerform + 264
	23  CoreFoundation                      0x000000019d392710 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
	24  CoreFoundation                      0x000000019d3926a4 __CFRunLoopDoSource0 + 176
	25  CoreFoundation                      0x000000019d392414 __CFRunLoopDoSources0 + 244
	26  CoreFoundation                      0x000000019d39101c __CFRunLoopRun + 828
	27  CoreFoundation                      0x000000019d39058c CFRunLoopRunSpecific + 612
	28  libjli.dylib                        0x0000000102abafec CreateExecutionEnvironment + 400
	29  libjli.dylib                        0x0000000102ab71fc JLI_Launch + 1184
	30  java                                0x0000000102a3fbac main + 400
	31  dyld                                0x000000019cf5bf28 start + 2236
)
Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest
16:21:52 [DASB Shutdown Hook] INFO  net.runee.gui.MainFrame - Goodbye!
```

i figured out that by changing my system's java version to an x86 version, it would finally launch. i don't mind using rosetta 2 with the bot, but by doing so the app is limited to java 16 and below, since after 17 java requires you to install the arm64 versions instead.

**Comment by BinkanSalaryman** [comment]
See build.gradle, around line [64](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/blob/master/build.gradle#L64) or [84](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/blob/master/build.gradle#L84). I've put together a sluggish attempt for an algorithm to detect architecture bit size for the bass natives, but it only works for windows. So yeah, quick and easy fix for you would be to replace lines 55-65 and 75-85 with `jvmArgs += '-Djava.library.path=natives/win64/'`.

From a side note, I wonder why the macOS instructions from spkane require building the software from source, I would expect the .jar file from the [releases ](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/releases/) page working just fine with the right command line arguments

**Comment by nbmusic098** [comment]
ok, replaced the lines in build.gradle & it built without a problem ! still only does versions over x86 java 16 but works flawless.

and as with launching with the jar file, it always crashes immediately with this regardless of java version
```
04:20:57 [main] INFO  net.runee.gui.MainFrame - Hello World!
04:20:57 [main] INFO  net.runee.misc.Utils - --------------------------
04:20:57 [main] INFO  net.runee.misc.Utils - Operating system: Mac OS X
04:20:57 [main] INFO  net.runee.misc.Utils - OS architecture : aarch64 
04:20:57 [main] INFO  net.runee.misc.Utils - Java version    : 19.0.2  
04:20:57 [main] INFO  net.runee.misc.Utils - Available cores : 12      
04:20:57 [main] INFO  net.runee.misc.Utils - Available memory: 16384 MB
04:20:57 [main] INFO  net.runee.misc.Utils - --------------------------
04:20:57 [main] ERROR net.runee.gui.MainFrame - Uncaught exception in thread main
jouvieje.bass.exceptions.BassException: no bass in java.library.path or org.lwjgl.librarypath
	at jouvieje.bass.BassInit.loadLibraries(BassInit.java:96)
	at net.runee.gui.MainFrame.main(MainFrame.java:55)
04:20:59 [DASB Shutdown Hook] INFO  net.runee.gui.MainFrame - Goodbye!

```

**Comment by BinkanSalaryman** [comment]
What are your parameters for launching the .jar file?
