### ISSUE TITLE
Failed to open recording device

### ISSUE THREAD

**Issue by INTJax** [BinkanSalaryman/Discord-Audio-Stream-Bot#81]
Bot remains muted in Discord regardless of mute status in the app.
Running on Windows Server 2019 version 1809
Java version 8.0.3810.9 (Java 8 Update 381)

When I toggle the mute button in the app I get the following error in the app.log:

12:06:07 [JDA MainWS-ReadThread] ERROR net.runee.DiscordAudioStreamBot - Failed to open recording device 'CABLE Output (VB-Audio Virtual '
net.runee.errors.BassException: Some mystery error
	at net.runee.misc.Utils.checkBassError(Utils.java:308)
	at net.runee.SpeakHandler.openRecordingDevice(SpeakHandler.java:71)
	at net.runee.DiscordAudioStreamBot.updateSpeakState(DiscordAudioStreamBot.java:399)
	at net.runee.DiscordAudioStreamBot.joinAudio(DiscordAudioStreamBot.java:331)
	at net.runee.commands.user.JoinAudioCommand.run(JoinAudioCommand.java:66)
	at net.runee.DiscordAudioStreamBot.onSlashCommandInteraction(DiscordAudioStreamBot.java:291)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:426)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:181)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:112)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:83)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:983)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:869)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:847)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1022)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by BinkanSalaryman** [comment]
Looks like the recording device name is cut off, can you try renaming it in the OS to something short, restart the bot program and reselect the device?
