### ISSUE TITLE
gradle build error in MacOS

### ISSUE THREAD

**Issue by bakemann** [BinkanSalaryman/Discord-Audio-Stream-Bot#83]
I am using m2Macbook.
When I run gradle build I get the following error and cannot complete the build.
I am using gradle 8.5 and Java 21.
(2023-05-31)
```
> Configure project :
Build file '/Users/bakemann/Desktop/Discord-Audio-Stream-Bot/build.gradle': line 16
The org.gradle.api.plugins.ApplicationPluginConvention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#application_convention_deprecation
        at build_7j4up4e9afndwty9s7x2789zm.run(/Users/bakemann/Desktop/Discord-Audio-Stream-Bot/build.gradle:16)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
Build file '/Users/bakemann/Desktop/Discord-Audio-Stream-Bot/build.gradle': line 16
The org.gradle.api.plugins.Convention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#deprecated_access_to_conventions
        at build_7j4up4e9afndwty9s7x2789zm.run(/Users/bakemann/Desktop/Discord-Audio-Stream-Bot/build.gradle:16)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
Build file '/Users/bakemann/Desktop/Discord-Audio-Stream-Bot/build.gradle': line 17
The org.gradle.api.plugins.JavaPluginConvention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#java_convention_deprecation
        at build_7j4up4e9afndwty9s7x2789zm.run(/Users/bakemann/Desktop/Discord-Audio-Stream-Bot/build.gradle:17)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
Build file '/Users/bakemann/Desktop/Discord-Audio-Stream-Bot/build.gradle': line 17
The org.gradle.api.plugins.Convention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#deprecated_access_to_conventions
        at build_7j4up4e9afndwty9s7x2789zm.run(/Users/bakemann/Desktop/Discord-Audio-Stream-Bot/build.gradle:17)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
Build file '/Users/bakemann/Desktop/Discord-Audio-Stream-Bot/build.gradle': line 18
The org.gradle.api.plugins.JavaPluginConvention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#java_convention_deprecation
        at build_7j4up4e9afndwty9s7x2789zm.run(/Users/bakemann/Desktop/Discord-Audio-Stream-Bot/build.gradle:18)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
Build file '/Users/bakemann/Desktop/Discord-Audio-Stream-Bot/build.gradle': line 18
The org.gradle.api.plugins.Convention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#deprecated_access_to_conventions
        at build_7j4up4e9afndwty9s7x2789zm.run(/Users/bakemann/Desktop/Discord-Audio-Stream-Bot/build.gradle:18)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/bakemann/Desktop/Discord-Audio-Stream-Bot/build.gradle' line: 64

* What went wrong:
A problem occurred evaluating root project 'Discord-Audio-Stream-Bot'.
> Unrecognized operating system: Mac OS X

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

**Comment by bakemann** [comment]
I was able to build on 
<img width="1230" alt="スクリーンショット 2023-12-17 4 42 37" src="https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/assets/90588595/7b9eef66-6440-4dea-945b-9aceb02eb76a">
2023-03-23, but I get this window and cannot start.

```04:41:43 [main] INFO  net.runee.gui.MainFrame - Hello World!
04:41:43 [main] INFO  net.runee.misc.Utils - --------------------------
04:41:43 [main] INFO  net.runee.misc.Utils - Operating system: Mac OS X
04:41:43 [main] INFO  net.runee.misc.Utils - OS architecture : aarch64 
04:41:43 [main] INFO  net.runee.misc.Utils - Java version    : 21.0.1  
04:41:43 [main] INFO  net.runee.misc.Utils - Available cores : 8       
04:41:43 [main] INFO  net.runee.misc.Utils - Available memory: 2048 MB 
04:41:43 [main] INFO  net.runee.misc.Utils - --------------------------
04:41:43 [main] ERROR net.runee.gui.MainFrame - Uncaught exception in thread main
jouvieje.bass.exceptions.BassException: no bass in java.library.path or org.lwjgl.librarypath
	at jouvieje.bass.BassInit.loadLibraries(BassInit.java:96)
	at net.runee.gui.MainFrame.main(MainFrame.java:55)
04:43:09 [DASB Shutdown Hook] INFO  net.runee.gui.MainFrame - Goodbye!
```

**Comment by BinkanSalaryman** [comment]
> jouvieje.bass.exceptions.BassException: no bass in java.library.path or org.lwjgl.librarypath

You have to provide the path to the bass (audio library) natives in the program arguments using `-Djava.library.path="natives/mac/"`.

( If you encounter an issue with unnamed modules (java9+), `--add-exports="java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED"` should do the trick. )
