### ISSUE TITLE
Error path

### ISSUE THREAD

**Issue by OwlBread** [BinkanSalaryman/Discord-Audio-Stream-Bot#89]
I apologize immediately for my bad English (I use a translator) 
I tried to run the program on a new win10 system, but it gives an error. I saw the solution in the program description, but I am too dumb to enter the specific path, can you please explain the solution more specifically? 

Error logs
17:10:55 [main] INFO net.runee.gui.MainFrame - Hello World!
17:10:55 [main] INFO net.runee.misc.Utils - ----------------------------
17:10:55 [main] INFO net.runee.misc.Utils - Operating system: Windows 10
17:10:55 [main] INFO net.runee.misc.Utils - OS architecture : x86       
17:10:55 [main] INFO net.runee.misc.Utils - Java version : 1.8.0_401 
17:10:55 [main] INFO net.runee.misc.Utils - Available cores : 8         
17:10:55 [main] INFO net.runee.misc.Utils - Available memory : 247 MB    
17:10:55 [main] INFO net.runee.misc.Utils - ----------------------------
17:10:55 [main] ERROR net.runee.gui.MainFrame - Uncaught exception in thread main
jouvieje.bass.exceptions.BassException: no bass in java.library.path or org.lwjgl.librarypath
	at jouvieje.bass.BassInit.loadLibraries(BassInit.java:96)
	at net.runee.gui.MainFrame.main(MainFrame.java:55)

Translated with DeepL.com (free version)

**Comment by BinkanSalaryman** [comment]
The program is unable to find the "bass" library native implementation files. Did you make sure the "run win.bat" file has a "natives" folder next to it?

**Comment by OwlBread** [comment]
![image](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/assets/158825496/61badf5b-f1d0-47f3-867b-6785b8448c1c)
yes

**Comment by WoozyMammoth** [comment]
I am also having the same issue. Natives folder is next to it.

**Comment by Accidental-Rogue** [comment]
Same here. Natives folder is next to run win.bat

**Comment by ElonMuts** [comment]
same issue here, anyone found a solution yet?

**Comment by ElonMuts** [comment]
If I run "run win.bat" as an administrator I get the error "unable to access jarfile Discord Audio Stream Bot.jar".
I've looked for solutions to that but haven't found any thusfar that worked.
