### ISSUE TITLE
error and shutdown when connecting to discord

### ISSUE THREAD

**Issue by Arterias1** [BinkanSalaryman/Discord-Audio-Stream-Bot#93]
Hi, cheers for making this program.
Since few weeks, it doesn't work anymore and shutdown when connecting to discord server

Here is the app.log

13:23:01 [main] INFO  net.runee.gui.MainFrame - Hello World!
13:23:01 [main] INFO  net.runee.misc.Utils - ----------------------------
13:23:01 [main] INFO  net.runee.misc.Utils - Operating system: Windows 11
13:23:01 [main] INFO  net.runee.misc.Utils - OS architecture : amd64     
13:23:01 [main] INFO  net.runee.misc.Utils - Java version    : 1.8.0_321 
13:23:01 [main] INFO  net.runee.misc.Utils - Available cores : 24        
13:23:01 [main] INFO  net.runee.misc.Utils - Available memory: 14530 MB  
13:23:01 [main] INFO  net.runee.misc.Utils - ----------------------------
13:23:03 [AWT-EventQueue-0] INFO  net.runee.DiscordAudioStreamBot - Logging in...
13:23:03 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Automatically disabled CacheFlags due to missing intents
13:23:03 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.ACTIVITY (missing GatewayIntent.GUILD_PRESENCES)
13:23:03 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.EMOJI (missing GatewayIntent.GUILD_EMOJIS_AND_STICKERS)
13:23:03 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.STICKER (missing GatewayIntent.GUILD_EMOJIS_AND_STICKERS)
13:23:03 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.CLIENT_STATUS (missing GatewayIntent.GUILD_PRESENCES)
13:23:03 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.ONLINE_STATUS (missing GatewayIntent.GUILD_PRESENCES)
13:23:03 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.SCHEDULED_EVENTS (missing GatewayIntent.SCHEDULED_EVENTS)
13:23:03 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - You can manually disable these flags to remove this warning by using disableCache(CacheFlag.ACTIVITY, CacheFlag.EMOJI, CacheFlag.STICKER, CacheFlag.CLIENT_STATUS, CacheFlag.ONLINE_STATUS, CacheFlag.SCHEDULED_EVENTS) on your JDABuilder
13:23:04 [JDA RateLimit-Worker 1] ERROR n.d.jda.internal.requests.Requester - There was an I/O error while executing a REST request: Cannot assign requested address: connect
13:23:04 [AWT-EventQueue-0] DEBUG n.d.j.internal.requests.RateLimiter - Removed 1 expired buckets
13:23:04 [AWT-EventQueue-0] INFO  net.runee.DiscordAudioStreamBot - Logged off
13:23:04 [AWT-EventQueue-0] ERROR net.runee.gui.MainFrame - Uncaught exception in thread AWT-EventQueue-0
net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: java.net.BindException
	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:230)
	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:632)
	at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:399)
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:323)
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:293)
	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1803)
	at net.runee.DiscordAudioStreamBot.login(DiscordAudioStreamBot.java:121)
	at net.runee.gui.components.HomePanel.loginButtonPressed(HomePanel.java:124)
	at net.runee.gui.components.HomePanel.lambda$initComponents$0(HomePanel.java:50)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.net.BindException: Cannot assign requested address: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:182)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:235)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:144)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:127)
	at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:492)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	Suppressed: java.net.BindException: Cannot assign requested address: connect
		... 37 common frames omitted
	Suppressed: java.net.BindException: Cannot assign requested address: connect
		... 37 common frames omitted
	Suppressed: java.net.BindException: Cannot assign requested address: connect
		... 37 common frames omitted
	Suppressed: java.net.BindException: Cannot assign requested address: connect
		... 37 common frames omitted
Caused by: net.dv8tion.jda.api.exceptions.ContextException: null
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:73)
	at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
	at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:212)
	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:222)
	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:632)
	at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:399)
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:323)
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:293)
	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1803)
	at net.runee.DiscordAudioStreamBot.login(DiscordAudioStreamBot.java:121)
	at net.runee.gui.components.HomePanel.loginButtonPressed(HomePanel.java:124)
	at net.runee.gui.components.HomePanel.lambda$initComponents$0(HomePanel.java:50)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
13:23:05 [DASB Shutdown Hook] INFO  net.runee.gui.MainFrame - Goodbye!

**Comment by Arterias1** [comment]
wasnt running the last release.

**Comment by Arterias1** [comment]
Hello! issue is back since few days, sharing the app.log:

`19:01:09 [main] INFO  net.runee.gui.MainFrame - Hello World!
19:01:09 [main] INFO  net.runee.misc.Utils - ----------------------------
19:01:09 [main] INFO  net.runee.misc.Utils - Operating system: Windows 11
19:01:09 [main] INFO  net.runee.misc.Utils - OS architecture : amd64     
19:01:09 [main] INFO  net.runee.misc.Utils - Java version    : 1.8.0_321 
19:01:09 [main] INFO  net.runee.misc.Utils - Available cores : 24        
19:01:09 [main] INFO  net.runee.misc.Utils - Available memory: 14530 MB  
19:01:09 [main] INFO  net.runee.misc.Utils - ----------------------------
19:01:11 [AWT-EventQueue-0] INFO  net.runee.DiscordAudioStreamBot - Logging in...
19:01:11 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Automatically disabled CacheFlags due to missing intents
19:01:11 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.ACTIVITY (missing GatewayIntent.GUILD_PRESENCES)
19:01:11 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.EMOJI (missing GatewayIntent.GUILD_EMOJIS_AND_STICKERS)
19:01:11 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.STICKER (missing GatewayIntent.GUILD_EMOJIS_AND_STICKERS)
19:01:11 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.CLIENT_STATUS (missing GatewayIntent.GUILD_PRESENCES)
19:01:11 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.ONLINE_STATUS (missing GatewayIntent.GUILD_PRESENCES)
19:01:11 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - Disabled CacheFlag.SCHEDULED_EVENTS (missing GatewayIntent.SCHEDULED_EVENTS)
19:01:11 [AWT-EventQueue-0] WARN  net.dv8tion.jda.api.JDA - You can manually disable these flags to remove this warning by using disableCache(CacheFlag.ACTIVITY, CacheFlag.EMOJI, CacheFlag.STICKER, CacheFlag.CLIENT_STATUS, CacheFlag.ONLINE_STATUS, CacheFlag.SCHEDULED_EVENTS) on your JDABuilder
19:01:11 [JDA RateLimit-Worker 1] ERROR n.d.jda.internal.requests.Requester - There was an I/O error while executing a REST request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
19:01:11 [AWT-EventQueue-0] DEBUG n.d.j.internal.requests.RateLimiter - Removed 1 expired buckets
19:01:11 [AWT-EventQueue-0] INFO  net.runee.DiscordAudioStreamBot - Logged off
19:01:11 [AWT-EventQueue-0] ERROR net.runee.gui.MainFrame - Uncaught exception in thread AWT-EventQueue-0
net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: javax.net.ssl.SSLHandshakeException
	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:230)
	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:632)
	at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:399)
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:323)
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:293)
	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1803)
	at net.runee.DiscordAudioStreamBot.login(DiscordAudioStreamBot.java:121)
	at net.runee.gui.components.HomePanel.loginButtonPressed(HomePanel.java:124)
	at net.runee.gui.components.HomePanel.lambda$initComponents$0(HomePanel.java:50)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Unknown Source)
	at sun.security.ssl.TransportContext.fatal(Unknown Source)
	at sun.security.ssl.TransportContext.fatal(Unknown Source)
	at sun.security.ssl.TransportContext.fatal(Unknown Source)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
	at sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at sun.security.ssl.SSLTransport.decode(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:182)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:144)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:127)
	at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:492)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 40 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)
	... 46 common frames omitted
Caused by: net.dv8tion.jda.api.exceptions.ContextException: null
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:73)
	at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
	at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:212)
	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:222)
	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:632)
	at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:399)
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:323)
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:293)
	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1803)
	at net.runee.DiscordAudioStreamBot.login(DiscordAudioStreamBot.java:121)
	at net.runee.gui.components.HomePanel.loginButtonPressed(HomePanel.java:124)
	at net.runee.gui.components.HomePanel.lambda$initComponents$0(HomePanel.java:50)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
19:01:16 [DASB Shutdown Hook] INFO  net.runee.gui.MainFrame - Goodbye!
`

**Comment by BinkanSalaryman** [comment]
I don't get this error while connecting to discord. The logs suggest there is an issue regarding certificates with your virtual machine to discord, if I understand it correctly. Maybe this thread can help you: https://stackoverflow.com/questions/9619030/resolving-javax-net-ssl-sslhandshakeexception-sun-security-validator-validatore
